import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { FileText, Search, ShieldCheck } from "lucide-react";
import { PageHeader } from "@/components/portal/ui";

export const Route = createFileRoute("/portal/disclosures")({
  head: () => ({
    meta: [
      { title: "Disclosures — approvU" },
      {
        name: "description",
        content:
          "Privacy policy, broker disclosure, conflict of interest, and FCAC cost-of-borrowing — versioned and timestamped.",
      },
    ],
  }),
  component: DisclosuresPage,
});

function DisclosuresPage() {
  const [q, setQ] = useState("");

  return (
    <>
      <PageHeader
        eyebrow="Compliance"
        title="Disclosures Library"
        description="Profile-level policies and application-specific disclosures, all versioned and timestamped."
      />

      <div className="rounded-2xl border border-border bg-card shadow-sm">
        <div className="flex flex-wrap items-center gap-2 border-b border-border p-3">
          <div className="flex flex-1 min-w-[200px] items-center gap-2 rounded-lg border border-border bg-background px-3 py-1.5">
            <Search className="h-4 w-4 text-muted-foreground" />
            <input
              value={q}
              onChange={(e) => setQ(e.target.value)}
              placeholder="Search disclosures…"
              className="w-full bg-transparent text-sm outline-none"
            />
          </div>
        </div>

        <div className="flex flex-col items-center gap-4 p-10 text-center">
          <div className="flex h-14 w-14 items-center justify-center rounded-full bg-muted">
            <FileText className="h-6 w-6 text-muted-foreground" />
          </div>
          <div>
            <p className="text-sm font-semibold text-foreground">
              No disclosures have been assigned to your account yet.
            </p>
            <p className="mt-2 max-w-md text-sm text-muted-foreground">
              Disclosures will appear here when generated by approvU or required by your mortgage
              application. Required consents can be completed in your Application workspace.
            </p>
          </div>
          <div className="flex flex-wrap justify-center gap-3">
            <Link
              to="/portal/applications"
              className="inline-flex items-center gap-1.5 rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90"
            >
              View application
            </Link>
            <Link
              to="/portal/applications"
              className="inline-flex items-center gap-1.5 rounded-md border border-border bg-background px-4 py-2 text-sm font-medium text-foreground hover:bg-muted"
            >
              Application consents
            </Link>
          </div>
          <div className="mt-2 flex items-center gap-2 text-[11px] text-muted-foreground">
            <ShieldCheck className="h-3.5 w-3.5" />
            All disclosures are versioned and timestamped.
          </div>
        </div>
      </div>
    </>
  );
}
