/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RefinanceRouteImport } from './routes/refinance'
import { Route as PurchaseRouteImport } from './routes/purchase'
import { Route as PrePurchaseRouteImport } from './routes/pre-purchase'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalWalletRouteImport } from './routes/portal.wallet'
import { Route as PortalToolsRouteImport } from './routes/portal.tools'
import { Route as PortalSettingsRouteImport } from './routes/portal.settings'
import { Route as InternalMortgageOffersRouteImport } from './routes/internal.mortgage-offers'
import { Route as InternalFullApplicationRouteImport } from './routes/internal.full-application'
import { Route as InternalBorrowerDashboardRouteImport } from './routes/internal.borrower-dashboard'
import { Route as InternalAccountHandoffRouteImport } from './routes/internal.account-handoff'
import { Route as PortalApplicationsIndexRouteImport } from './routes/portal.applications.index'
import { Route as PortalToolsStressTestRouteImport } from './routes/portal.tools.stress-test'
import { Route as PortalToolsScenarioCompareRouteImport } from './routes/portal.tools.scenario-compare'
import { Route as PortalToolsRentVsBuyRouteImport } from './routes/portal.tools.rent-vs-buy'
import { Route as PortalToolsRenewalComparisonRouteImport } from './routes/portal.tools.renewal-comparison'
import { Route as PortalToolsRefinanceSavingsRouteImport } from './routes/portal.tools.refinance-savings'
import { Route as PortalToolsPrepaymentRouteImport } from './routes/portal.tools.prepayment'
import { Route as PortalToolsPaymentCalculatorRouteImport } from './routes/portal.tools.payment-calculator'
import { Route as PortalToolsHomeEquityRouteImport } from './routes/portal.tools.home-equity'
import { Route as PortalToolsDownPaymentRouteImport } from './routes/portal.tools.down-payment'
import { Route as PortalToolsDebtConsolidationRouteImport } from './routes/portal.tools.debt-consolidation'
import { Route as PortalToolsClosingCostsRouteImport } from './routes/portal.tools.closing-costs'
import { Route as PortalToolsAffordabilityRouteImport } from './routes/portal.tools.affordability'
import { Route as PortalSettingsSecurityRouteImport } from './routes/portal.settings.security'
import { Route as PortalSettingsProfileRouteImport } from './routes/portal.settings.profile'
import { Route as PortalSettingsPrivacyRouteImport } from './routes/portal.settings.privacy'
import { Route as PortalSettingsPreferencesRouteImport } from './routes/portal.settings.preferences'
import { Route as PortalSettingsPaymentMethodsRouteImport } from './routes/portal.settings.payment-methods'
import { Route as PortalSettingsNotificationsRouteImport } from './routes/portal.settings.notifications'
import { Route as ApplicationsApplicationIdSubmitRouteImport } from './routes/applications.$applicationId.submit'
import { Route as ApplicationsApplicationIdPropertyFinancingRouteImport } from './routes/applications.$applicationId.property-financing'
import { Route as ApplicationsApplicationIdProductReviewConsentRouteImport } from './routes/applications.$applicationId.product-review-consent'
import { Route as ApplicationsApplicationIdProductPriorityRouteImport } from './routes/applications.$applicationId.product-priority'
import { Route as ApplicationsApplicationIdMortgageRequestRouteImport } from './routes/applications.$applicationId.mortgage-request'
import { Route as ApplicationsApplicationIdMortgageOffersRouteImport } from './routes/applications.$applicationId.mortgage-offers'
import { Route as PortalApplicationsApplicationIdQualificationSummaryRouteImport } from './routes/portal.applications.$applicationId.qualification-summary'
import { Route as ApplicationsApplicationIdPropertyFinancingTargetPropertyRouteImport } from './routes/applications.$applicationId.property-financing.target-property'
import { Route as ApplicationsApplicationIdPropertyFinancingRenewalPreferencesRouteImport } from './routes/applications.$applicationId.property-financing.renewal-preferences'
import { Route as ApplicationsApplicationIdPropertyFinancingRefinanceRequestRouteImport } from './routes/applications.$applicationId.property-financing.refinance-request'
import { Route as ApplicationsApplicationIdPropertyFinancingPurchasePlanRouteImport } from './routes/applications.$applicationId.property-financing.purchase-plan'
import { Route as ApplicationsApplicationIdPropertyFinancingPropertyRouteImport } from './routes/applications.$applicationId.property-financing.property'
import { Route as ApplicationsApplicationIdPropertyFinancingDownPaymentRouteImport } from './routes/applications.$applicationId.property-financing.down-payment'
import { Route as ApplicationsApplicationIdPropertyFinancingCurrentMortgageRouteImport } from './routes/applications.$applicationId.property-financing.current-mortgage'

const RefinanceRoute = RefinanceRouteImport.update({
  id: '/refinance',
  path: '/refinance',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRoute = PurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const PrePurchaseRoute = PrePurchaseRouteImport.update({
  id: '/pre-purchase',
  path: '/pre-purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalWalletRoute = PortalWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => PortalRoute,
} as any)
const PortalToolsRoute = PortalToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSettingsRoute = PortalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PortalRoute,
} as any)
const InternalMortgageOffersRoute = InternalMortgageOffersRouteImport.update({
  id: '/internal/mortgage-offers',
  path: '/internal/mortgage-offers',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalFullApplicationRoute = InternalFullApplicationRouteImport.update({
  id: '/internal/full-application',
  path: '/internal/full-application',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalBorrowerDashboardRoute =
  InternalBorrowerDashboardRouteImport.update({
    id: '/internal/borrower-dashboard',
    path: '/internal/borrower-dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const InternalAccountHandoffRoute = InternalAccountHandoffRouteImport.update({
  id: '/internal/account-handoff',
  path: '/internal/account-handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalApplicationsIndexRoute = PortalApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalToolsStressTestRoute = PortalToolsStressTestRouteImport.update({
  id: '/stress-test',
  path: '/stress-test',
  getParentRoute: () => PortalToolsRoute,
} as any)
const PortalToolsScenarioCompareRoute =
  PortalToolsScenarioCompareRouteImport.update({
    id: '/scenario-compare',
    path: '/scenario-compare',
    getParentRoute: () => PortalToolsRoute,
  } as any)
const PortalToolsRentVsBuyRoute = PortalToolsRentVsBuyRouteImport.update({
  id: '/rent-vs-buy',
  path: '/rent-vs-buy',
  getParentRoute: () => PortalToolsRoute,
} as any)
const PortalToolsRenewalComparisonRoute =
  PortalToolsRenewalComparisonRouteImport.update({
    id: '/renewal-comparison',
    path: '/renewal-comparison',
    getParentRoute: () => PortalToolsRoute,
  } as any)
const PortalToolsRefinanceSavingsRoute =
  PortalToolsRefinanceSavingsRouteImport.update({
    id: '/refinance-savings',
    path: '/refinance-savings',
    getParentRoute: () => PortalToolsRoute,
  } as any)
const PortalToolsPrepaymentRoute = PortalToolsPrepaymentRouteImport.update({
  id: '/prepayment',
  path: '/prepayment',
  getParentRoute: () => PortalToolsRoute,
} as any)
const PortalToolsPaymentCalculatorRoute =
  PortalToolsPaymentCalculatorRouteImport.update({
    id: '/payment-calculator',
    path: '/payment-calculator',
    getParentRoute: () => PortalToolsRoute,
  } as any)
const PortalToolsHomeEquityRoute = PortalToolsHomeEquityRouteImport.update({
  id: '/home-equity',
  path: '/home-equity',
  getParentRoute: () => PortalToolsRoute,
} as any)
const PortalToolsDownPaymentRoute = PortalToolsDownPaymentRouteImport.update({
  id: '/down-payment',
  path: '/down-payment',
  getParentRoute: () => PortalToolsRoute,
} as any)
const PortalToolsDebtConsolidationRoute =
  PortalToolsDebtConsolidationRouteImport.update({
    id: '/debt-consolidation',
    path: '/debt-consolidation',
    getParentRoute: () => PortalToolsRoute,
  } as any)
const PortalToolsClosingCostsRoute = PortalToolsClosingCostsRouteImport.update({
  id: '/closing-costs',
  path: '/closing-costs',
  getParentRoute: () => PortalToolsRoute,
} as any)
const PortalToolsAffordabilityRoute =
  PortalToolsAffordabilityRouteImport.update({
    id: '/affordability',
    path: '/affordability',
    getParentRoute: () => PortalToolsRoute,
  } as any)
const PortalSettingsSecurityRoute = PortalSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => PortalSettingsRoute,
} as any)
const PortalSettingsProfileRoute = PortalSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalSettingsRoute,
} as any)
const PortalSettingsPrivacyRoute = PortalSettingsPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PortalSettingsRoute,
} as any)
const PortalSettingsPreferencesRoute =
  PortalSettingsPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => PortalSettingsRoute,
  } as any)
const PortalSettingsPaymentMethodsRoute =
  PortalSettingsPaymentMethodsRouteImport.update({
    id: '/payment-methods',
    path: '/payment-methods',
    getParentRoute: () => PortalSettingsRoute,
  } as any)
const PortalSettingsNotificationsRoute =
  PortalSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => PortalSettingsRoute,
  } as any)
const ApplicationsApplicationIdSubmitRoute =
  ApplicationsApplicationIdSubmitRouteImport.update({
    id: '/applications/$applicationId/submit',
    path: '/applications/$applicationId/submit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApplicationsApplicationIdPropertyFinancingRoute =
  ApplicationsApplicationIdPropertyFinancingRouteImport.update({
    id: '/applications/$applicationId/property-financing',
    path: '/applications/$applicationId/property-financing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApplicationsApplicationIdProductReviewConsentRoute =
  ApplicationsApplicationIdProductReviewConsentRouteImport.update({
    id: '/applications/$applicationId/product-review-consent',
    path: '/applications/$applicationId/product-review-consent',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApplicationsApplicationIdProductPriorityRoute =
  ApplicationsApplicationIdProductPriorityRouteImport.update({
    id: '/applications/$applicationId/product-priority',
    path: '/applications/$applicationId/product-priority',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApplicationsApplicationIdMortgageRequestRoute =
  ApplicationsApplicationIdMortgageRequestRouteImport.update({
    id: '/applications/$applicationId/mortgage-request',
    path: '/applications/$applicationId/mortgage-request',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApplicationsApplicationIdMortgageOffersRoute =
  ApplicationsApplicationIdMortgageOffersRouteImport.update({
    id: '/applications/$applicationId/mortgage-offers',
    path: '/applications/$applicationId/mortgage-offers',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortalApplicationsApplicationIdQualificationSummaryRoute =
  PortalApplicationsApplicationIdQualificationSummaryRouteImport.update({
    id: '/applications/$applicationId/qualification-summary',
    path: '/applications/$applicationId/qualification-summary',
    getParentRoute: () => PortalRoute,
  } as any)
const ApplicationsApplicationIdPropertyFinancingTargetPropertyRoute =
  ApplicationsApplicationIdPropertyFinancingTargetPropertyRouteImport.update({
    id: '/target-property',
    path: '/target-property',
    getParentRoute: () => ApplicationsApplicationIdPropertyFinancingRoute,
  } as any)
const ApplicationsApplicationIdPropertyFinancingRenewalPreferencesRoute =
  ApplicationsApplicationIdPropertyFinancingRenewalPreferencesRouteImport.update(
    {
      id: '/renewal-preferences',
      path: '/renewal-preferences',
      getParentRoute: () => ApplicationsApplicationIdPropertyFinancingRoute,
    } as any,
  )
const ApplicationsApplicationIdPropertyFinancingRefinanceRequestRoute =
  ApplicationsApplicationIdPropertyFinancingRefinanceRequestRouteImport.update({
    id: '/refinance-request',
    path: '/refinance-request',
    getParentRoute: () => ApplicationsApplicationIdPropertyFinancingRoute,
  } as any)
const ApplicationsApplicationIdPropertyFinancingPurchasePlanRoute =
  ApplicationsApplicationIdPropertyFinancingPurchasePlanRouteImport.update({
    id: '/purchase-plan',
    path: '/purchase-plan',
    getParentRoute: () => ApplicationsApplicationIdPropertyFinancingRoute,
  } as any)
const ApplicationsApplicationIdPropertyFinancingPropertyRoute =
  ApplicationsApplicationIdPropertyFinancingPropertyRouteImport.update({
    id: '/property',
    path: '/property',
    getParentRoute: () => ApplicationsApplicationIdPropertyFinancingRoute,
  } as any)
const ApplicationsApplicationIdPropertyFinancingDownPaymentRoute =
  ApplicationsApplicationIdPropertyFinancingDownPaymentRouteImport.update({
    id: '/down-payment',
    path: '/down-payment',
    getParentRoute: () => ApplicationsApplicationIdPropertyFinancingRoute,
  } as any)
const ApplicationsApplicationIdPropertyFinancingCurrentMortgageRoute =
  ApplicationsApplicationIdPropertyFinancingCurrentMortgageRouteImport.update({
    id: '/current-mortgage',
    path: '/current-mortgage',
    getParentRoute: () => ApplicationsApplicationIdPropertyFinancingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteWithChildren
  '/pre-purchase': typeof PrePurchaseRoute
  '/purchase': typeof PurchaseRoute
  '/refinance': typeof RefinanceRoute
  '/internal/account-handoff': typeof InternalAccountHandoffRoute
  '/internal/borrower-dashboard': typeof InternalBorrowerDashboardRoute
  '/internal/full-application': typeof InternalFullApplicationRoute
  '/internal/mortgage-offers': typeof InternalMortgageOffersRoute
  '/portal/settings': typeof PortalSettingsRouteWithChildren
  '/portal/tools': typeof PortalToolsRouteWithChildren
  '/portal/wallet': typeof PortalWalletRoute
  '/portal/': typeof PortalIndexRoute
  '/applications/$applicationId/mortgage-offers': typeof ApplicationsApplicationIdMortgageOffersRoute
  '/applications/$applicationId/mortgage-request': typeof ApplicationsApplicationIdMortgageRequestRoute
  '/applications/$applicationId/product-priority': typeof ApplicationsApplicationIdProductPriorityRoute
  '/applications/$applicationId/product-review-consent': typeof ApplicationsApplicationIdProductReviewConsentRoute
  '/applications/$applicationId/property-financing': typeof ApplicationsApplicationIdPropertyFinancingRouteWithChildren
  '/applications/$applicationId/submit': typeof ApplicationsApplicationIdSubmitRoute
  '/portal/settings/notifications': typeof PortalSettingsNotificationsRoute
  '/portal/settings/payment-methods': typeof PortalSettingsPaymentMethodsRoute
  '/portal/settings/preferences': typeof PortalSettingsPreferencesRoute
  '/portal/settings/privacy': typeof PortalSettingsPrivacyRoute
  '/portal/settings/profile': typeof PortalSettingsProfileRoute
  '/portal/settings/security': typeof PortalSettingsSecurityRoute
  '/portal/tools/affordability': typeof PortalToolsAffordabilityRoute
  '/portal/tools/closing-costs': typeof PortalToolsClosingCostsRoute
  '/portal/tools/debt-consolidation': typeof PortalToolsDebtConsolidationRoute
  '/portal/tools/down-payment': typeof PortalToolsDownPaymentRoute
  '/portal/tools/home-equity': typeof PortalToolsHomeEquityRoute
  '/portal/tools/payment-calculator': typeof PortalToolsPaymentCalculatorRoute
  '/portal/tools/prepayment': typeof PortalToolsPrepaymentRoute
  '/portal/tools/refinance-savings': typeof PortalToolsRefinanceSavingsRoute
  '/portal/tools/renewal-comparison': typeof PortalToolsRenewalComparisonRoute
  '/portal/tools/rent-vs-buy': typeof PortalToolsRentVsBuyRoute
  '/portal/tools/scenario-compare': typeof PortalToolsScenarioCompareRoute
  '/portal/tools/stress-test': typeof PortalToolsStressTestRoute
  '/portal/applications/': typeof PortalApplicationsIndexRoute
  '/applications/$applicationId/property-financing/current-mortgage': typeof ApplicationsApplicationIdPropertyFinancingCurrentMortgageRoute
  '/applications/$applicationId/property-financing/down-payment': typeof ApplicationsApplicationIdPropertyFinancingDownPaymentRoute
  '/applications/$applicationId/property-financing/property': typeof ApplicationsApplicationIdPropertyFinancingPropertyRoute
  '/applications/$applicationId/property-financing/purchase-plan': typeof ApplicationsApplicationIdPropertyFinancingPurchasePlanRoute
  '/applications/$applicationId/property-financing/refinance-request': typeof ApplicationsApplicationIdPropertyFinancingRefinanceRequestRoute
  '/applications/$applicationId/property-financing/renewal-preferences': typeof ApplicationsApplicationIdPropertyFinancingRenewalPreferencesRoute
  '/applications/$applicationId/property-financing/target-property': typeof ApplicationsApplicationIdPropertyFinancingTargetPropertyRoute
  '/portal/applications/$applicationId/qualification-summary': typeof PortalApplicationsApplicationIdQualificationSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pre-purchase': typeof PrePurchaseRoute
  '/purchase': typeof PurchaseRoute
  '/refinance': typeof RefinanceRoute
  '/internal/account-handoff': typeof InternalAccountHandoffRoute
  '/internal/borrower-dashboard': typeof InternalBorrowerDashboardRoute
  '/internal/full-application': typeof InternalFullApplicationRoute
  '/internal/mortgage-offers': typeof InternalMortgageOffersRoute
  '/portal/settings': typeof PortalSettingsRouteWithChildren
  '/portal/tools': typeof PortalToolsRouteWithChildren
  '/portal/wallet': typeof PortalWalletRoute
  '/portal': typeof PortalIndexRoute
  '/applications/$applicationId/mortgage-offers': typeof ApplicationsApplicationIdMortgageOffersRoute
  '/applications/$applicationId/mortgage-request': typeof ApplicationsApplicationIdMortgageRequestRoute
  '/applications/$applicationId/product-priority': typeof ApplicationsApplicationIdProductPriorityRoute
  '/applications/$applicationId/product-review-consent': typeof ApplicationsApplicationIdProductReviewConsentRoute
  '/applications/$applicationId/property-financing': typeof ApplicationsApplicationIdPropertyFinancingRouteWithChildren
  '/applications/$applicationId/submit': typeof ApplicationsApplicationIdSubmitRoute
  '/portal/settings/notifications': typeof PortalSettingsNotificationsRoute
  '/portal/settings/payment-methods': typeof PortalSettingsPaymentMethodsRoute
  '/portal/settings/preferences': typeof PortalSettingsPreferencesRoute
  '/portal/settings/privacy': typeof PortalSettingsPrivacyRoute
  '/portal/settings/profile': typeof PortalSettingsProfileRoute
  '/portal/settings/security': typeof PortalSettingsSecurityRoute
  '/portal/tools/affordability': typeof PortalToolsAffordabilityRoute
  '/portal/tools/closing-costs': typeof PortalToolsClosingCostsRoute
  '/portal/tools/debt-consolidation': typeof PortalToolsDebtConsolidationRoute
  '/portal/tools/down-payment': typeof PortalToolsDownPaymentRoute
  '/portal/tools/home-equity': typeof PortalToolsHomeEquityRoute
  '/portal/tools/payment-calculator': typeof PortalToolsPaymentCalculatorRoute
  '/portal/tools/prepayment': typeof PortalToolsPrepaymentRoute
  '/portal/tools/refinance-savings': typeof PortalToolsRefinanceSavingsRoute
  '/portal/tools/renewal-comparison': typeof PortalToolsRenewalComparisonRoute
  '/portal/tools/rent-vs-buy': typeof PortalToolsRentVsBuyRoute
  '/portal/tools/scenario-compare': typeof PortalToolsScenarioCompareRoute
  '/portal/tools/stress-test': typeof PortalToolsStressTestRoute
  '/portal/applications': typeof PortalApplicationsIndexRoute
  '/applications/$applicationId/property-financing/current-mortgage': typeof ApplicationsApplicationIdPropertyFinancingCurrentMortgageRoute
  '/applications/$applicationId/property-financing/down-payment': typeof ApplicationsApplicationIdPropertyFinancingDownPaymentRoute
  '/applications/$applicationId/property-financing/property': typeof ApplicationsApplicationIdPropertyFinancingPropertyRoute
  '/applications/$applicationId/property-financing/purchase-plan': typeof ApplicationsApplicationIdPropertyFinancingPurchasePlanRoute
  '/applications/$applicationId/property-financing/refinance-request': typeof ApplicationsApplicationIdPropertyFinancingRefinanceRequestRoute
  '/applications/$applicationId/property-financing/renewal-preferences': typeof ApplicationsApplicationIdPropertyFinancingRenewalPreferencesRoute
  '/applications/$applicationId/property-financing/target-property': typeof ApplicationsApplicationIdPropertyFinancingTargetPropertyRoute
  '/portal/applications/$applicationId/qualification-summary': typeof PortalApplicationsApplicationIdQualificationSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteWithChildren
  '/pre-purchase': typeof PrePurchaseRoute
  '/purchase': typeof PurchaseRoute
  '/refinance': typeof RefinanceRoute
  '/internal/account-handoff': typeof InternalAccountHandoffRoute
  '/internal/borrower-dashboard': typeof InternalBorrowerDashboardRoute
  '/internal/full-application': typeof InternalFullApplicationRoute
  '/internal/mortgage-offers': typeof InternalMortgageOffersRoute
  '/portal/settings': typeof PortalSettingsRouteWithChildren
  '/portal/tools': typeof PortalToolsRouteWithChildren
  '/portal/wallet': typeof PortalWalletRoute
  '/portal/': typeof PortalIndexRoute
  '/applications/$applicationId/mortgage-offers': typeof ApplicationsApplicationIdMortgageOffersRoute
  '/applications/$applicationId/mortgage-request': typeof ApplicationsApplicationIdMortgageRequestRoute
  '/applications/$applicationId/product-priority': typeof ApplicationsApplicationIdProductPriorityRoute
  '/applications/$applicationId/product-review-consent': typeof ApplicationsApplicationIdProductReviewConsentRoute
  '/applications/$applicationId/property-financing': typeof ApplicationsApplicationIdPropertyFinancingRouteWithChildren
  '/applications/$applicationId/submit': typeof ApplicationsApplicationIdSubmitRoute
  '/portal/settings/notifications': typeof PortalSettingsNotificationsRoute
  '/portal/settings/payment-methods': typeof PortalSettingsPaymentMethodsRoute
  '/portal/settings/preferences': typeof PortalSettingsPreferencesRoute
  '/portal/settings/privacy': typeof PortalSettingsPrivacyRoute
  '/portal/settings/profile': typeof PortalSettingsProfileRoute
  '/portal/settings/security': typeof PortalSettingsSecurityRoute
  '/portal/tools/affordability': typeof PortalToolsAffordabilityRoute
  '/portal/tools/closing-costs': typeof PortalToolsClosingCostsRoute
  '/portal/tools/debt-consolidation': typeof PortalToolsDebtConsolidationRoute
  '/portal/tools/down-payment': typeof PortalToolsDownPaymentRoute
  '/portal/tools/home-equity': typeof PortalToolsHomeEquityRoute
  '/portal/tools/payment-calculator': typeof PortalToolsPaymentCalculatorRoute
  '/portal/tools/prepayment': typeof PortalToolsPrepaymentRoute
  '/portal/tools/refinance-savings': typeof PortalToolsRefinanceSavingsRoute
  '/portal/tools/renewal-comparison': typeof PortalToolsRenewalComparisonRoute
  '/portal/tools/rent-vs-buy': typeof PortalToolsRentVsBuyRoute
  '/portal/tools/scenario-compare': typeof PortalToolsScenarioCompareRoute
  '/portal/tools/stress-test': typeof PortalToolsStressTestRoute
  '/portal/applications/': typeof PortalApplicationsIndexRoute
  '/applications/$applicationId/property-financing/current-mortgage': typeof ApplicationsApplicationIdPropertyFinancingCurrentMortgageRoute
  '/applications/$applicationId/property-financing/down-payment': typeof ApplicationsApplicationIdPropertyFinancingDownPaymentRoute
  '/applications/$applicationId/property-financing/property': typeof ApplicationsApplicationIdPropertyFinancingPropertyRoute
  '/applications/$applicationId/property-financing/purchase-plan': typeof ApplicationsApplicationIdPropertyFinancingPurchasePlanRoute
  '/applications/$applicationId/property-financing/refinance-request': typeof ApplicationsApplicationIdPropertyFinancingRefinanceRequestRoute
  '/applications/$applicationId/property-financing/renewal-preferences': typeof ApplicationsApplicationIdPropertyFinancingRenewalPreferencesRoute
  '/applications/$applicationId/property-financing/target-property': typeof ApplicationsApplicationIdPropertyFinancingTargetPropertyRoute
  '/portal/applications/$applicationId/qualification-summary': typeof PortalApplicationsApplicationIdQualificationSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/portal'
    | '/pre-purchase'
    | '/purchase'
    | '/refinance'
    | '/internal/account-handoff'
    | '/internal/borrower-dashboard'
    | '/internal/full-application'
    | '/internal/mortgage-offers'
    | '/portal/settings'
    | '/portal/tools'
    | '/portal/wallet'
    | '/portal/'
    | '/applications/$applicationId/mortgage-offers'
    | '/applications/$applicationId/mortgage-request'
    | '/applications/$applicationId/product-priority'
    | '/applications/$applicationId/product-review-consent'
    | '/applications/$applicationId/property-financing'
    | '/applications/$applicationId/submit'
    | '/portal/settings/notifications'
    | '/portal/settings/payment-methods'
    | '/portal/settings/preferences'
    | '/portal/settings/privacy'
    | '/portal/settings/profile'
    | '/portal/settings/security'
    | '/portal/tools/affordability'
    | '/portal/tools/closing-costs'
    | '/portal/tools/debt-consolidation'
    | '/portal/tools/down-payment'
    | '/portal/tools/home-equity'
    | '/portal/tools/payment-calculator'
    | '/portal/tools/prepayment'
    | '/portal/tools/refinance-savings'
    | '/portal/tools/renewal-comparison'
    | '/portal/tools/rent-vs-buy'
    | '/portal/tools/scenario-compare'
    | '/portal/tools/stress-test'
    | '/portal/applications/'
    | '/applications/$applicationId/property-financing/current-mortgage'
    | '/applications/$applicationId/property-financing/down-payment'
    | '/applications/$applicationId/property-financing/property'
    | '/applications/$applicationId/property-financing/purchase-plan'
    | '/applications/$applicationId/property-financing/refinance-request'
    | '/applications/$applicationId/property-financing/renewal-preferences'
    | '/applications/$applicationId/property-financing/target-property'
    | '/portal/applications/$applicationId/qualification-summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pre-purchase'
    | '/purchase'
    | '/refinance'
    | '/internal/account-handoff'
    | '/internal/borrower-dashboard'
    | '/internal/full-application'
    | '/internal/mortgage-offers'
    | '/portal/settings'
    | '/portal/tools'
    | '/portal/wallet'
    | '/portal'
    | '/applications/$applicationId/mortgage-offers'
    | '/applications/$applicationId/mortgage-request'
    | '/applications/$applicationId/product-priority'
    | '/applications/$applicationId/product-review-consent'
    | '/applications/$applicationId/property-financing'
    | '/applications/$applicationId/submit'
    | '/portal/settings/notifications'
    | '/portal/settings/payment-methods'
    | '/portal/settings/preferences'
    | '/portal/settings/privacy'
    | '/portal/settings/profile'
    | '/portal/settings/security'
    | '/portal/tools/affordability'
    | '/portal/tools/closing-costs'
    | '/portal/tools/debt-consolidation'
    | '/portal/tools/down-payment'
    | '/portal/tools/home-equity'
    | '/portal/tools/payment-calculator'
    | '/portal/tools/prepayment'
    | '/portal/tools/refinance-savings'
    | '/portal/tools/renewal-comparison'
    | '/portal/tools/rent-vs-buy'
    | '/portal/tools/scenario-compare'
    | '/portal/tools/stress-test'
    | '/portal/applications'
    | '/applications/$applicationId/property-financing/current-mortgage'
    | '/applications/$applicationId/property-financing/down-payment'
    | '/applications/$applicationId/property-financing/property'
    | '/applications/$applicationId/property-financing/purchase-plan'
    | '/applications/$applicationId/property-financing/refinance-request'
    | '/applications/$applicationId/property-financing/renewal-preferences'
    | '/applications/$applicationId/property-financing/target-property'
    | '/portal/applications/$applicationId/qualification-summary'
  id:
    | '__root__'
    | '/'
    | '/portal'
    | '/pre-purchase'
    | '/purchase'
    | '/refinance'
    | '/internal/account-handoff'
    | '/internal/borrower-dashboard'
    | '/internal/full-application'
    | '/internal/mortgage-offers'
    | '/portal/settings'
    | '/portal/tools'
    | '/portal/wallet'
    | '/portal/'
    | '/applications/$applicationId/mortgage-offers'
    | '/applications/$applicationId/mortgage-request'
    | '/applications/$applicationId/product-priority'
    | '/applications/$applicationId/product-review-consent'
    | '/applications/$applicationId/property-financing'
    | '/applications/$applicationId/submit'
    | '/portal/settings/notifications'
    | '/portal/settings/payment-methods'
    | '/portal/settings/preferences'
    | '/portal/settings/privacy'
    | '/portal/settings/profile'
    | '/portal/settings/security'
    | '/portal/tools/affordability'
    | '/portal/tools/closing-costs'
    | '/portal/tools/debt-consolidation'
    | '/portal/tools/down-payment'
    | '/portal/tools/home-equity'
    | '/portal/tools/payment-calculator'
    | '/portal/tools/prepayment'
    | '/portal/tools/refinance-savings'
    | '/portal/tools/renewal-comparison'
    | '/portal/tools/rent-vs-buy'
    | '/portal/tools/scenario-compare'
    | '/portal/tools/stress-test'
    | '/portal/applications/'
    | '/applications/$applicationId/property-financing/current-mortgage'
    | '/applications/$applicationId/property-financing/down-payment'
    | '/applications/$applicationId/property-financing/property'
    | '/applications/$applicationId/property-financing/purchase-plan'
    | '/applications/$applicationId/property-financing/refinance-request'
    | '/applications/$applicationId/property-financing/renewal-preferences'
    | '/applications/$applicationId/property-financing/target-property'
    | '/portal/applications/$applicationId/qualification-summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalRoute: typeof PortalRouteWithChildren
  PrePurchaseRoute: typeof PrePurchaseRoute
  PurchaseRoute: typeof PurchaseRoute
  RefinanceRoute: typeof RefinanceRoute
  InternalAccountHandoffRoute: typeof InternalAccountHandoffRoute
  InternalBorrowerDashboardRoute: typeof InternalBorrowerDashboardRoute
  InternalFullApplicationRoute: typeof InternalFullApplicationRoute
  InternalMortgageOffersRoute: typeof InternalMortgageOffersRoute
  ApplicationsApplicationIdMortgageOffersRoute: typeof ApplicationsApplicationIdMortgageOffersRoute
  ApplicationsApplicationIdMortgageRequestRoute: typeof ApplicationsApplicationIdMortgageRequestRoute
  ApplicationsApplicationIdProductPriorityRoute: typeof ApplicationsApplicationIdProductPriorityRoute
  ApplicationsApplicationIdProductReviewConsentRoute: typeof ApplicationsApplicationIdProductReviewConsentRoute
  ApplicationsApplicationIdPropertyFinancingRoute: typeof ApplicationsApplicationIdPropertyFinancingRouteWithChildren
  ApplicationsApplicationIdSubmitRoute: typeof ApplicationsApplicationIdSubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/refinance': {
      id: '/refinance'
      path: '/refinance'
      fullPath: '/refinance'
      preLoaderRoute: typeof RefinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase': {
      id: '/purchase'
      path: '/purchase'
      fullPath: '/purchase'
      preLoaderRoute: typeof PurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-purchase': {
      id: '/pre-purchase'
      path: '/pre-purchase'
      fullPath: '/pre-purchase'
      preLoaderRoute: typeof PrePurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/wallet': {
      id: '/portal/wallet'
      path: '/wallet'
      fullPath: '/portal/wallet'
      preLoaderRoute: typeof PortalWalletRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/tools': {
      id: '/portal/tools'
      path: '/tools'
      fullPath: '/portal/tools'
      preLoaderRoute: typeof PortalToolsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/settings': {
      id: '/portal/settings'
      path: '/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof PortalSettingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/internal/mortgage-offers': {
      id: '/internal/mortgage-offers'
      path: '/internal/mortgage-offers'
      fullPath: '/internal/mortgage-offers'
      preLoaderRoute: typeof InternalMortgageOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/full-application': {
      id: '/internal/full-application'
      path: '/internal/full-application'
      fullPath: '/internal/full-application'
      preLoaderRoute: typeof InternalFullApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/borrower-dashboard': {
      id: '/internal/borrower-dashboard'
      path: '/internal/borrower-dashboard'
      fullPath: '/internal/borrower-dashboard'
      preLoaderRoute: typeof InternalBorrowerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/account-handoff': {
      id: '/internal/account-handoff'
      path: '/internal/account-handoff'
      fullPath: '/internal/account-handoff'
      preLoaderRoute: typeof InternalAccountHandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/applications/': {
      id: '/portal/applications/'
      path: '/applications'
      fullPath: '/portal/applications/'
      preLoaderRoute: typeof PortalApplicationsIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/tools/stress-test': {
      id: '/portal/tools/stress-test'
      path: '/stress-test'
      fullPath: '/portal/tools/stress-test'
      preLoaderRoute: typeof PortalToolsStressTestRouteImport
      parentRoute: typeof PortalToolsRoute
    }
    '/portal/tools/scenario-compare': {
      id: '/portal/tools/scenario-compare'
      path: '/scenario-compare'
      fullPath: '/portal/tools/scenario-compare'
      preLoaderRoute: typeof PortalToolsScenarioCompareRouteImport
      parentRoute: typeof PortalToolsRoute
    }
    '/portal/tools/rent-vs-buy': {
      id: '/portal/tools/rent-vs-buy'
      path: '/rent-vs-buy'
      fullPath: '/portal/tools/rent-vs-buy'
      preLoaderRoute: typeof PortalToolsRentVsBuyRouteImport
      parentRoute: typeof PortalToolsRoute
    }
    '/portal/tools/renewal-comparison': {
      id: '/portal/tools/renewal-comparison'
      path: '/renewal-comparison'
      fullPath: '/portal/tools/renewal-comparison'
      preLoaderRoute: typeof PortalToolsRenewalComparisonRouteImport
      parentRoute: typeof PortalToolsRoute
    }
    '/portal/tools/refinance-savings': {
      id: '/portal/tools/refinance-savings'
      path: '/refinance-savings'
      fullPath: '/portal/tools/refinance-savings'
      preLoaderRoute: typeof PortalToolsRefinanceSavingsRouteImport
      parentRoute: typeof PortalToolsRoute
    }
    '/portal/tools/prepayment': {
      id: '/portal/tools/prepayment'
      path: '/prepayment'
      fullPath: '/portal/tools/prepayment'
      preLoaderRoute: typeof PortalToolsPrepaymentRouteImport
      parentRoute: typeof PortalToolsRoute
    }
    '/portal/tools/payment-calculator': {
      id: '/portal/tools/payment-calculator'
      path: '/payment-calculator'
      fullPath: '/portal/tools/payment-calculator'
      preLoaderRoute: typeof PortalToolsPaymentCalculatorRouteImport
      parentRoute: typeof PortalToolsRoute
    }
    '/portal/tools/home-equity': {
      id: '/portal/tools/home-equity'
      path: '/home-equity'
      fullPath: '/portal/tools/home-equity'
      preLoaderRoute: typeof PortalToolsHomeEquityRouteImport
      parentRoute: typeof PortalToolsRoute
    }
    '/portal/tools/down-payment': {
      id: '/portal/tools/down-payment'
      path: '/down-payment'
      fullPath: '/portal/tools/down-payment'
      preLoaderRoute: typeof PortalToolsDownPaymentRouteImport
      parentRoute: typeof PortalToolsRoute
    }
    '/portal/tools/debt-consolidation': {
      id: '/portal/tools/debt-consolidation'
      path: '/debt-consolidation'
      fullPath: '/portal/tools/debt-consolidation'
      preLoaderRoute: typeof PortalToolsDebtConsolidationRouteImport
      parentRoute: typeof PortalToolsRoute
    }
    '/portal/tools/closing-costs': {
      id: '/portal/tools/closing-costs'
      path: '/closing-costs'
      fullPath: '/portal/tools/closing-costs'
      preLoaderRoute: typeof PortalToolsClosingCostsRouteImport
      parentRoute: typeof PortalToolsRoute
    }
    '/portal/tools/affordability': {
      id: '/portal/tools/affordability'
      path: '/affordability'
      fullPath: '/portal/tools/affordability'
      preLoaderRoute: typeof PortalToolsAffordabilityRouteImport
      parentRoute: typeof PortalToolsRoute
    }
    '/portal/settings/security': {
      id: '/portal/settings/security'
      path: '/security'
      fullPath: '/portal/settings/security'
      preLoaderRoute: typeof PortalSettingsSecurityRouteImport
      parentRoute: typeof PortalSettingsRoute
    }
    '/portal/settings/profile': {
      id: '/portal/settings/profile'
      path: '/profile'
      fullPath: '/portal/settings/profile'
      preLoaderRoute: typeof PortalSettingsProfileRouteImport
      parentRoute: typeof PortalSettingsRoute
    }
    '/portal/settings/privacy': {
      id: '/portal/settings/privacy'
      path: '/privacy'
      fullPath: '/portal/settings/privacy'
      preLoaderRoute: typeof PortalSettingsPrivacyRouteImport
      parentRoute: typeof PortalSettingsRoute
    }
    '/portal/settings/preferences': {
      id: '/portal/settings/preferences'
      path: '/preferences'
      fullPath: '/portal/settings/preferences'
      preLoaderRoute: typeof PortalSettingsPreferencesRouteImport
      parentRoute: typeof PortalSettingsRoute
    }
    '/portal/settings/payment-methods': {
      id: '/portal/settings/payment-methods'
      path: '/payment-methods'
      fullPath: '/portal/settings/payment-methods'
      preLoaderRoute: typeof PortalSettingsPaymentMethodsRouteImport
      parentRoute: typeof PortalSettingsRoute
    }
    '/portal/settings/notifications': {
      id: '/portal/settings/notifications'
      path: '/notifications'
      fullPath: '/portal/settings/notifications'
      preLoaderRoute: typeof PortalSettingsNotificationsRouteImport
      parentRoute: typeof PortalSettingsRoute
    }
    '/applications/$applicationId/submit': {
      id: '/applications/$applicationId/submit'
      path: '/applications/$applicationId/submit'
      fullPath: '/applications/$applicationId/submit'
      preLoaderRoute: typeof ApplicationsApplicationIdSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$applicationId/property-financing': {
      id: '/applications/$applicationId/property-financing'
      path: '/applications/$applicationId/property-financing'
      fullPath: '/applications/$applicationId/property-financing'
      preLoaderRoute: typeof ApplicationsApplicationIdPropertyFinancingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$applicationId/product-review-consent': {
      id: '/applications/$applicationId/product-review-consent'
      path: '/applications/$applicationId/product-review-consent'
      fullPath: '/applications/$applicationId/product-review-consent'
      preLoaderRoute: typeof ApplicationsApplicationIdProductReviewConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$applicationId/product-priority': {
      id: '/applications/$applicationId/product-priority'
      path: '/applications/$applicationId/product-priority'
      fullPath: '/applications/$applicationId/product-priority'
      preLoaderRoute: typeof ApplicationsApplicationIdProductPriorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$applicationId/mortgage-request': {
      id: '/applications/$applicationId/mortgage-request'
      path: '/applications/$applicationId/mortgage-request'
      fullPath: '/applications/$applicationId/mortgage-request'
      preLoaderRoute: typeof ApplicationsApplicationIdMortgageRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$applicationId/mortgage-offers': {
      id: '/applications/$applicationId/mortgage-offers'
      path: '/applications/$applicationId/mortgage-offers'
      fullPath: '/applications/$applicationId/mortgage-offers'
      preLoaderRoute: typeof ApplicationsApplicationIdMortgageOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/applications/$applicationId/qualification-summary': {
      id: '/portal/applications/$applicationId/qualification-summary'
      path: '/applications/$applicationId/qualification-summary'
      fullPath: '/portal/applications/$applicationId/qualification-summary'
      preLoaderRoute: typeof PortalApplicationsApplicationIdQualificationSummaryRouteImport
      parentRoute: typeof PortalRoute
    }
    '/applications/$applicationId/property-financing/target-property': {
      id: '/applications/$applicationId/property-financing/target-property'
      path: '/target-property'
      fullPath: '/applications/$applicationId/property-financing/target-property'
      preLoaderRoute: typeof ApplicationsApplicationIdPropertyFinancingTargetPropertyRouteImport
      parentRoute: typeof ApplicationsApplicationIdPropertyFinancingRoute
    }
    '/applications/$applicationId/property-financing/renewal-preferences': {
      id: '/applications/$applicationId/property-financing/renewal-preferences'
      path: '/renewal-preferences'
      fullPath: '/applications/$applicationId/property-financing/renewal-preferences'
      preLoaderRoute: typeof ApplicationsApplicationIdPropertyFinancingRenewalPreferencesRouteImport
      parentRoute: typeof ApplicationsApplicationIdPropertyFinancingRoute
    }
    '/applications/$applicationId/property-financing/refinance-request': {
      id: '/applications/$applicationId/property-financing/refinance-request'
      path: '/refinance-request'
      fullPath: '/applications/$applicationId/property-financing/refinance-request'
      preLoaderRoute: typeof ApplicationsApplicationIdPropertyFinancingRefinanceRequestRouteImport
      parentRoute: typeof ApplicationsApplicationIdPropertyFinancingRoute
    }
    '/applications/$applicationId/property-financing/purchase-plan': {
      id: '/applications/$applicationId/property-financing/purchase-plan'
      path: '/purchase-plan'
      fullPath: '/applications/$applicationId/property-financing/purchase-plan'
      preLoaderRoute: typeof ApplicationsApplicationIdPropertyFinancingPurchasePlanRouteImport
      parentRoute: typeof ApplicationsApplicationIdPropertyFinancingRoute
    }
    '/applications/$applicationId/property-financing/property': {
      id: '/applications/$applicationId/property-financing/property'
      path: '/property'
      fullPath: '/applications/$applicationId/property-financing/property'
      preLoaderRoute: typeof ApplicationsApplicationIdPropertyFinancingPropertyRouteImport
      parentRoute: typeof ApplicationsApplicationIdPropertyFinancingRoute
    }
    '/applications/$applicationId/property-financing/down-payment': {
      id: '/applications/$applicationId/property-financing/down-payment'
      path: '/down-payment'
      fullPath: '/applications/$applicationId/property-financing/down-payment'
      preLoaderRoute: typeof ApplicationsApplicationIdPropertyFinancingDownPaymentRouteImport
      parentRoute: typeof ApplicationsApplicationIdPropertyFinancingRoute
    }
    '/applications/$applicationId/property-financing/current-mortgage': {
      id: '/applications/$applicationId/property-financing/current-mortgage'
      path: '/current-mortgage'
      fullPath: '/applications/$applicationId/property-financing/current-mortgage'
      preLoaderRoute: typeof ApplicationsApplicationIdPropertyFinancingCurrentMortgageRouteImport
      parentRoute: typeof ApplicationsApplicationIdPropertyFinancingRoute
    }
  }
}

interface PortalSettingsRouteChildren {
  PortalSettingsNotificationsRoute: typeof PortalSettingsNotificationsRoute
  PortalSettingsPaymentMethodsRoute: typeof PortalSettingsPaymentMethodsRoute
  PortalSettingsPreferencesRoute: typeof PortalSettingsPreferencesRoute
  PortalSettingsPrivacyRoute: typeof PortalSettingsPrivacyRoute
  PortalSettingsProfileRoute: typeof PortalSettingsProfileRoute
  PortalSettingsSecurityRoute: typeof PortalSettingsSecurityRoute
}

const PortalSettingsRouteChildren: PortalSettingsRouteChildren = {
  PortalSettingsNotificationsRoute: PortalSettingsNotificationsRoute,
  PortalSettingsPaymentMethodsRoute: PortalSettingsPaymentMethodsRoute,
  PortalSettingsPreferencesRoute: PortalSettingsPreferencesRoute,
  PortalSettingsPrivacyRoute: PortalSettingsPrivacyRoute,
  PortalSettingsProfileRoute: PortalSettingsProfileRoute,
  PortalSettingsSecurityRoute: PortalSettingsSecurityRoute,
}

const PortalSettingsRouteWithChildren = PortalSettingsRoute._addFileChildren(
  PortalSettingsRouteChildren,
)

interface PortalToolsRouteChildren {
  PortalToolsAffordabilityRoute: typeof PortalToolsAffordabilityRoute
  PortalToolsClosingCostsRoute: typeof PortalToolsClosingCostsRoute
  PortalToolsDebtConsolidationRoute: typeof PortalToolsDebtConsolidationRoute
  PortalToolsDownPaymentRoute: typeof PortalToolsDownPaymentRoute
  PortalToolsHomeEquityRoute: typeof PortalToolsHomeEquityRoute
  PortalToolsPaymentCalculatorRoute: typeof PortalToolsPaymentCalculatorRoute
  PortalToolsPrepaymentRoute: typeof PortalToolsPrepaymentRoute
  PortalToolsRefinanceSavingsRoute: typeof PortalToolsRefinanceSavingsRoute
  PortalToolsRenewalComparisonRoute: typeof PortalToolsRenewalComparisonRoute
  PortalToolsRentVsBuyRoute: typeof PortalToolsRentVsBuyRoute
  PortalToolsScenarioCompareRoute: typeof PortalToolsScenarioCompareRoute
  PortalToolsStressTestRoute: typeof PortalToolsStressTestRoute
}

const PortalToolsRouteChildren: PortalToolsRouteChildren = {
  PortalToolsAffordabilityRoute: PortalToolsAffordabilityRoute,
  PortalToolsClosingCostsRoute: PortalToolsClosingCostsRoute,
  PortalToolsDebtConsolidationRoute: PortalToolsDebtConsolidationRoute,
  PortalToolsDownPaymentRoute: PortalToolsDownPaymentRoute,
  PortalToolsHomeEquityRoute: PortalToolsHomeEquityRoute,
  PortalToolsPaymentCalculatorRoute: PortalToolsPaymentCalculatorRoute,
  PortalToolsPrepaymentRoute: PortalToolsPrepaymentRoute,
  PortalToolsRefinanceSavingsRoute: PortalToolsRefinanceSavingsRoute,
  PortalToolsRenewalComparisonRoute: PortalToolsRenewalComparisonRoute,
  PortalToolsRentVsBuyRoute: PortalToolsRentVsBuyRoute,
  PortalToolsScenarioCompareRoute: PortalToolsScenarioCompareRoute,
  PortalToolsStressTestRoute: PortalToolsStressTestRoute,
}

const PortalToolsRouteWithChildren = PortalToolsRoute._addFileChildren(
  PortalToolsRouteChildren,
)

interface PortalRouteChildren {
  PortalSettingsRoute: typeof PortalSettingsRouteWithChildren
  PortalToolsRoute: typeof PortalToolsRouteWithChildren
  PortalWalletRoute: typeof PortalWalletRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalApplicationsIndexRoute: typeof PortalApplicationsIndexRoute
  PortalApplicationsApplicationIdQualificationSummaryRoute: typeof PortalApplicationsApplicationIdQualificationSummaryRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalSettingsRoute: PortalSettingsRouteWithChildren,
  PortalToolsRoute: PortalToolsRouteWithChildren,
  PortalWalletRoute: PortalWalletRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalApplicationsIndexRoute: PortalApplicationsIndexRoute,
  PortalApplicationsApplicationIdQualificationSummaryRoute:
    PortalApplicationsApplicationIdQualificationSummaryRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface ApplicationsApplicationIdPropertyFinancingRouteChildren {
  ApplicationsApplicationIdPropertyFinancingCurrentMortgageRoute: typeof ApplicationsApplicationIdPropertyFinancingCurrentMortgageRoute
  ApplicationsApplicationIdPropertyFinancingDownPaymentRoute: typeof ApplicationsApplicationIdPropertyFinancingDownPaymentRoute
  ApplicationsApplicationIdPropertyFinancingPropertyRoute: typeof ApplicationsApplicationIdPropertyFinancingPropertyRoute
  ApplicationsApplicationIdPropertyFinancingPurchasePlanRoute: typeof ApplicationsApplicationIdPropertyFinancingPurchasePlanRoute
  ApplicationsApplicationIdPropertyFinancingRefinanceRequestRoute: typeof ApplicationsApplicationIdPropertyFinancingRefinanceRequestRoute
  ApplicationsApplicationIdPropertyFinancingRenewalPreferencesRoute: typeof ApplicationsApplicationIdPropertyFinancingRenewalPreferencesRoute
  ApplicationsApplicationIdPropertyFinancingTargetPropertyRoute: typeof ApplicationsApplicationIdPropertyFinancingTargetPropertyRoute
}

const ApplicationsApplicationIdPropertyFinancingRouteChildren: ApplicationsApplicationIdPropertyFinancingRouteChildren =
  {
    ApplicationsApplicationIdPropertyFinancingCurrentMortgageRoute:
      ApplicationsApplicationIdPropertyFinancingCurrentMortgageRoute,
    ApplicationsApplicationIdPropertyFinancingDownPaymentRoute:
      ApplicationsApplicationIdPropertyFinancingDownPaymentRoute,
    ApplicationsApplicationIdPropertyFinancingPropertyRoute:
      ApplicationsApplicationIdPropertyFinancingPropertyRoute,
    ApplicationsApplicationIdPropertyFinancingPurchasePlanRoute:
      ApplicationsApplicationIdPropertyFinancingPurchasePlanRoute,
    ApplicationsApplicationIdPropertyFinancingRefinanceRequestRoute:
      ApplicationsApplicationIdPropertyFinancingRefinanceRequestRoute,
    ApplicationsApplicationIdPropertyFinancingRenewalPreferencesRoute:
      ApplicationsApplicationIdPropertyFinancingRenewalPreferencesRoute,
    ApplicationsApplicationIdPropertyFinancingTargetPropertyRoute:
      ApplicationsApplicationIdPropertyFinancingTargetPropertyRoute,
  }

const ApplicationsApplicationIdPropertyFinancingRouteWithChildren =
  ApplicationsApplicationIdPropertyFinancingRoute._addFileChildren(
    ApplicationsApplicationIdPropertyFinancingRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalRoute: PortalRouteWithChildren,
  PrePurchaseRoute: PrePurchaseRoute,
  PurchaseRoute: PurchaseRoute,
  RefinanceRoute: RefinanceRoute,
  InternalAccountHandoffRoute: InternalAccountHandoffRoute,
  InternalBorrowerDashboardRoute: InternalBorrowerDashboardRoute,
  InternalFullApplicationRoute: InternalFullApplicationRoute,
  InternalMortgageOffersRoute: InternalMortgageOffersRoute,
  ApplicationsApplicationIdMortgageOffersRoute:
    ApplicationsApplicationIdMortgageOffersRoute,
  ApplicationsApplicationIdMortgageRequestRoute:
    ApplicationsApplicationIdMortgageRequestRoute,
  ApplicationsApplicationIdProductPriorityRoute:
    ApplicationsApplicationIdProductPriorityRoute,
  ApplicationsApplicationIdProductReviewConsentRoute:
    ApplicationsApplicationIdProductReviewConsentRoute,
  ApplicationsApplicationIdPropertyFinancingRoute:
    ApplicationsApplicationIdPropertyFinancingRouteWithChildren,
  ApplicationsApplicationIdSubmitRoute: ApplicationsApplicationIdSubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
