/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RefinanceRouteImport } from './routes/refinance'
import { Route as PurchaseRouteImport } from './routes/purchase'
import { Route as PrePurchaseRouteImport } from './routes/pre-purchase'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalSettingsRouteImport } from './routes/portal.settings'
import { Route as InternalMortgageOffersRouteImport } from './routes/internal.mortgage-offers'
import { Route as InternalFullApplicationRouteImport } from './routes/internal.full-application'
import { Route as InternalBorrowerDashboardRouteImport } from './routes/internal.borrower-dashboard'
import { Route as InternalAccountHandoffRouteImport } from './routes/internal.account-handoff'
import { Route as PortalSettingsProfileRouteImport } from './routes/portal.settings.profile'
import { Route as PortalApplicationsApplicationIdQualificationSummaryRouteImport } from './routes/portal.applications.$applicationId.qualification-summary'

const RefinanceRoute = RefinanceRouteImport.update({
  id: '/refinance',
  path: '/refinance',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRoute = PurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const PrePurchaseRoute = PrePurchaseRouteImport.update({
  id: '/pre-purchase',
  path: '/pre-purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalSettingsRoute = PortalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PortalRoute,
} as any)
const InternalMortgageOffersRoute = InternalMortgageOffersRouteImport.update({
  id: '/internal/mortgage-offers',
  path: '/internal/mortgage-offers',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalFullApplicationRoute = InternalFullApplicationRouteImport.update({
  id: '/internal/full-application',
  path: '/internal/full-application',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalBorrowerDashboardRoute =
  InternalBorrowerDashboardRouteImport.update({
    id: '/internal/borrower-dashboard',
    path: '/internal/borrower-dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const InternalAccountHandoffRoute = InternalAccountHandoffRouteImport.update({
  id: '/internal/account-handoff',
  path: '/internal/account-handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalSettingsProfileRoute = PortalSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalSettingsRoute,
} as any)
const PortalApplicationsApplicationIdQualificationSummaryRoute =
  PortalApplicationsApplicationIdQualificationSummaryRouteImport.update({
    id: '/applications/$applicationId/qualification-summary',
    path: '/applications/$applicationId/qualification-summary',
    getParentRoute: () => PortalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteWithChildren
  '/pre-purchase': typeof PrePurchaseRoute
  '/purchase': typeof PurchaseRoute
  '/refinance': typeof RefinanceRoute
  '/internal/account-handoff': typeof InternalAccountHandoffRoute
  '/internal/borrower-dashboard': typeof InternalBorrowerDashboardRoute
  '/internal/full-application': typeof InternalFullApplicationRoute
  '/internal/mortgage-offers': typeof InternalMortgageOffersRoute
  '/portal/settings': typeof PortalSettingsRouteWithChildren
  '/portal/settings/profile': typeof PortalSettingsProfileRoute
  '/portal/applications/$applicationId/qualification-summary': typeof PortalApplicationsApplicationIdQualificationSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteWithChildren
  '/pre-purchase': typeof PrePurchaseRoute
  '/purchase': typeof PurchaseRoute
  '/refinance': typeof RefinanceRoute
  '/internal/account-handoff': typeof InternalAccountHandoffRoute
  '/internal/borrower-dashboard': typeof InternalBorrowerDashboardRoute
  '/internal/full-application': typeof InternalFullApplicationRoute
  '/internal/mortgage-offers': typeof InternalMortgageOffersRoute
  '/portal/settings': typeof PortalSettingsRouteWithChildren
  '/portal/settings/profile': typeof PortalSettingsProfileRoute
  '/portal/applications/$applicationId/qualification-summary': typeof PortalApplicationsApplicationIdQualificationSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteWithChildren
  '/pre-purchase': typeof PrePurchaseRoute
  '/purchase': typeof PurchaseRoute
  '/refinance': typeof RefinanceRoute
  '/internal/account-handoff': typeof InternalAccountHandoffRoute
  '/internal/borrower-dashboard': typeof InternalBorrowerDashboardRoute
  '/internal/full-application': typeof InternalFullApplicationRoute
  '/internal/mortgage-offers': typeof InternalMortgageOffersRoute
  '/portal/settings': typeof PortalSettingsRouteWithChildren
  '/portal/settings/profile': typeof PortalSettingsProfileRoute
  '/portal/applications/$applicationId/qualification-summary': typeof PortalApplicationsApplicationIdQualificationSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/portal'
    | '/pre-purchase'
    | '/purchase'
    | '/refinance'
    | '/internal/account-handoff'
    | '/internal/borrower-dashboard'
    | '/internal/full-application'
    | '/internal/mortgage-offers'
    | '/portal/settings'
    | '/portal/settings/profile'
    | '/portal/applications/$applicationId/qualification-summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/portal'
    | '/pre-purchase'
    | '/purchase'
    | '/refinance'
    | '/internal/account-handoff'
    | '/internal/borrower-dashboard'
    | '/internal/full-application'
    | '/internal/mortgage-offers'
    | '/portal/settings'
    | '/portal/settings/profile'
    | '/portal/applications/$applicationId/qualification-summary'
  id:
    | '__root__'
    | '/'
    | '/portal'
    | '/pre-purchase'
    | '/purchase'
    | '/refinance'
    | '/internal/account-handoff'
    | '/internal/borrower-dashboard'
    | '/internal/full-application'
    | '/internal/mortgage-offers'
    | '/portal/settings'
    | '/portal/settings/profile'
    | '/portal/applications/$applicationId/qualification-summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalRoute: typeof PortalRouteWithChildren
  PrePurchaseRoute: typeof PrePurchaseRoute
  PurchaseRoute: typeof PurchaseRoute
  RefinanceRoute: typeof RefinanceRoute
  InternalAccountHandoffRoute: typeof InternalAccountHandoffRoute
  InternalBorrowerDashboardRoute: typeof InternalBorrowerDashboardRoute
  InternalFullApplicationRoute: typeof InternalFullApplicationRoute
  InternalMortgageOffersRoute: typeof InternalMortgageOffersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/refinance': {
      id: '/refinance'
      path: '/refinance'
      fullPath: '/refinance'
      preLoaderRoute: typeof RefinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase': {
      id: '/purchase'
      path: '/purchase'
      fullPath: '/purchase'
      preLoaderRoute: typeof PurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-purchase': {
      id: '/pre-purchase'
      path: '/pre-purchase'
      fullPath: '/pre-purchase'
      preLoaderRoute: typeof PrePurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/settings': {
      id: '/portal/settings'
      path: '/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof PortalSettingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/internal/mortgage-offers': {
      id: '/internal/mortgage-offers'
      path: '/internal/mortgage-offers'
      fullPath: '/internal/mortgage-offers'
      preLoaderRoute: typeof InternalMortgageOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/full-application': {
      id: '/internal/full-application'
      path: '/internal/full-application'
      fullPath: '/internal/full-application'
      preLoaderRoute: typeof InternalFullApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/borrower-dashboard': {
      id: '/internal/borrower-dashboard'
      path: '/internal/borrower-dashboard'
      fullPath: '/internal/borrower-dashboard'
      preLoaderRoute: typeof InternalBorrowerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/account-handoff': {
      id: '/internal/account-handoff'
      path: '/internal/account-handoff'
      fullPath: '/internal/account-handoff'
      preLoaderRoute: typeof InternalAccountHandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/settings/profile': {
      id: '/portal/settings/profile'
      path: '/profile'
      fullPath: '/portal/settings/profile'
      preLoaderRoute: typeof PortalSettingsProfileRouteImport
      parentRoute: typeof PortalSettingsRoute
    }
    '/portal/applications/$applicationId/qualification-summary': {
      id: '/portal/applications/$applicationId/qualification-summary'
      path: '/applications/$applicationId/qualification-summary'
      fullPath: '/portal/applications/$applicationId/qualification-summary'
      preLoaderRoute: typeof PortalApplicationsApplicationIdQualificationSummaryRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface PortalSettingsRouteChildren {
  PortalSettingsProfileRoute: typeof PortalSettingsProfileRoute
}

const PortalSettingsRouteChildren: PortalSettingsRouteChildren = {
  PortalSettingsProfileRoute: PortalSettingsProfileRoute,
}

const PortalSettingsRouteWithChildren = PortalSettingsRoute._addFileChildren(
  PortalSettingsRouteChildren,
)

interface PortalRouteChildren {
  PortalSettingsRoute: typeof PortalSettingsRouteWithChildren
  PortalApplicationsApplicationIdQualificationSummaryRoute: typeof PortalApplicationsApplicationIdQualificationSummaryRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalSettingsRoute: PortalSettingsRouteWithChildren,
  PortalApplicationsApplicationIdQualificationSummaryRoute:
    PortalApplicationsApplicationIdQualificationSummaryRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalRoute: PortalRouteWithChildren,
  PrePurchaseRoute: PrePurchaseRoute,
  PurchaseRoute: PurchaseRoute,
  RefinanceRoute: RefinanceRoute,
  InternalAccountHandoffRoute: InternalAccountHandoffRoute,
  InternalBorrowerDashboardRoute: InternalBorrowerDashboardRoute,
  InternalFullApplicationRoute: InternalFullApplicationRoute,
  InternalMortgageOffersRoute: InternalMortgageOffersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
