/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RefinanceRouteImport } from './routes/refinance'
import { Route as PurchaseRouteImport } from './routes/purchase'
import { Route as PrePurchaseRouteImport } from './routes/pre-purchase'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalSettingsRouteImport } from './routes/portal.settings'
import { Route as InternalMortgageOffersRouteImport } from './routes/internal.mortgage-offers'
import { Route as InternalFullApplicationRouteImport } from './routes/internal.full-application'
import { Route as InternalBorrowerDashboardRouteImport } from './routes/internal.borrower-dashboard'
import { Route as InternalAccountHandoffRouteImport } from './routes/internal.account-handoff'

const RefinanceRoute = RefinanceRouteImport.update({
  id: '/refinance',
  path: '/refinance',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRoute = PurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const PrePurchaseRoute = PrePurchaseRouteImport.update({
  id: '/pre-purchase',
  path: '/pre-purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalSettingsRoute = PortalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PortalRoute,
} as any)
const InternalMortgageOffersRoute = InternalMortgageOffersRouteImport.update({
  id: '/internal/mortgage-offers',
  path: '/internal/mortgage-offers',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalFullApplicationRoute = InternalFullApplicationRouteImport.update({
  id: '/internal/full-application',
  path: '/internal/full-application',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalBorrowerDashboardRoute =
  InternalBorrowerDashboardRouteImport.update({
    id: '/internal/borrower-dashboard',
    path: '/internal/borrower-dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const InternalAccountHandoffRoute = InternalAccountHandoffRouteImport.update({
  id: '/internal/account-handoff',
  path: '/internal/account-handoff',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteWithChildren
  '/pre-purchase': typeof PrePurchaseRoute
  '/purchase': typeof PurchaseRoute
  '/refinance': typeof RefinanceRoute
  '/internal/account-handoff': typeof InternalAccountHandoffRoute
  '/internal/borrower-dashboard': typeof InternalBorrowerDashboardRoute
  '/internal/full-application': typeof InternalFullApplicationRoute
  '/internal/mortgage-offers': typeof InternalMortgageOffersRoute
  '/portal/settings': typeof PortalSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteWithChildren
  '/pre-purchase': typeof PrePurchaseRoute
  '/purchase': typeof PurchaseRoute
  '/refinance': typeof RefinanceRoute
  '/internal/account-handoff': typeof InternalAccountHandoffRoute
  '/internal/borrower-dashboard': typeof InternalBorrowerDashboardRoute
  '/internal/full-application': typeof InternalFullApplicationRoute
  '/internal/mortgage-offers': typeof InternalMortgageOffersRoute
  '/portal/settings': typeof PortalSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteWithChildren
  '/pre-purchase': typeof PrePurchaseRoute
  '/purchase': typeof PurchaseRoute
  '/refinance': typeof RefinanceRoute
  '/internal/account-handoff': typeof InternalAccountHandoffRoute
  '/internal/borrower-dashboard': typeof InternalBorrowerDashboardRoute
  '/internal/full-application': typeof InternalFullApplicationRoute
  '/internal/mortgage-offers': typeof InternalMortgageOffersRoute
  '/portal/settings': typeof PortalSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/portal'
    | '/pre-purchase'
    | '/purchase'
    | '/refinance'
    | '/internal/account-handoff'
    | '/internal/borrower-dashboard'
    | '/internal/full-application'
    | '/internal/mortgage-offers'
    | '/portal/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/portal'
    | '/pre-purchase'
    | '/purchase'
    | '/refinance'
    | '/internal/account-handoff'
    | '/internal/borrower-dashboard'
    | '/internal/full-application'
    | '/internal/mortgage-offers'
    | '/portal/settings'
  id:
    | '__root__'
    | '/'
    | '/portal'
    | '/pre-purchase'
    | '/purchase'
    | '/refinance'
    | '/internal/account-handoff'
    | '/internal/borrower-dashboard'
    | '/internal/full-application'
    | '/internal/mortgage-offers'
    | '/portal/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalRoute: typeof PortalRouteWithChildren
  PrePurchaseRoute: typeof PrePurchaseRoute
  PurchaseRoute: typeof PurchaseRoute
  RefinanceRoute: typeof RefinanceRoute
  InternalAccountHandoffRoute: typeof InternalAccountHandoffRoute
  InternalBorrowerDashboardRoute: typeof InternalBorrowerDashboardRoute
  InternalFullApplicationRoute: typeof InternalFullApplicationRoute
  InternalMortgageOffersRoute: typeof InternalMortgageOffersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/refinance': {
      id: '/refinance'
      path: '/refinance'
      fullPath: '/refinance'
      preLoaderRoute: typeof RefinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase': {
      id: '/purchase'
      path: '/purchase'
      fullPath: '/purchase'
      preLoaderRoute: typeof PurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-purchase': {
      id: '/pre-purchase'
      path: '/pre-purchase'
      fullPath: '/pre-purchase'
      preLoaderRoute: typeof PrePurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/settings': {
      id: '/portal/settings'
      path: '/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof PortalSettingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/internal/mortgage-offers': {
      id: '/internal/mortgage-offers'
      path: '/internal/mortgage-offers'
      fullPath: '/internal/mortgage-offers'
      preLoaderRoute: typeof InternalMortgageOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/full-application': {
      id: '/internal/full-application'
      path: '/internal/full-application'
      fullPath: '/internal/full-application'
      preLoaderRoute: typeof InternalFullApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/borrower-dashboard': {
      id: '/internal/borrower-dashboard'
      path: '/internal/borrower-dashboard'
      fullPath: '/internal/borrower-dashboard'
      preLoaderRoute: typeof InternalBorrowerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/account-handoff': {
      id: '/internal/account-handoff'
      path: '/internal/account-handoff'
      fullPath: '/internal/account-handoff'
      preLoaderRoute: typeof InternalAccountHandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PortalRouteChildren {
  PortalSettingsRoute: typeof PortalSettingsRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalSettingsRoute: PortalSettingsRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalRoute: PortalRouteWithChildren,
  PrePurchaseRoute: PrePurchaseRoute,
  PurchaseRoute: PurchaseRoute,
  RefinanceRoute: RefinanceRoute,
  InternalAccountHandoffRoute: InternalAccountHandoffRoute,
  InternalBorrowerDashboardRoute: InternalBorrowerDashboardRoute,
  InternalFullApplicationRoute: InternalFullApplicationRoute,
  InternalMortgageOffersRoute: InternalMortgageOffersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
